### demo 1 - get all users
GET http://localhost:8080/demo1/users

### demo 1 - get user by id
GET http://localhost:8080/demo1/users/2


### demo 2 - get all users
GET http://localhost:8080/demo2/users

### demo 2 - get user by id
GET http://localhost:8080/demo2/users/2
